### ISSUE TITLE
修改网站主题字体

### ISSUE THREAD

**Issue by Littlemyself** [Littlemyself/blog#16]
[Telegram: 2]: # 'https://cdn.jsdelivr.net/gh/Littlemyself/imgvoid@master/wp-content/uploads/2021/09/图片.jpg'
对于自己的博客很多人都喜欢整一些好看的样式，字体也就是另一种选择添加也不想样式那样的困难。

### 找到喜欢的字体并引用
```css
### 参考网址
https://fonts.google.com/
http://www.googlefonts.cn/
```
```css
<link href="https://fonts.lug.ustc.edu.cn/css2?family=Ma+Shan+Zheng&family=Pacifico&display=swap" ;="" rel="stylesheet">
```
```css
h2 {
font-family:'Pacifico',Arial,'Ma Shan Zheng',Helvetica;
/*font-weight可以不要看需要*/
font-weight:400;
}
```
link放在主题的底部设置——网站底部自定义JS代码——粘贴进去（一行一个） font-family放在主题的顶部设置——自定义CSS样式代码——以上为参考h2按需要修改

### 完成效果：↓
<img src="https://cdn.jsdelivr.net/gh/Littlemyself/hmfgu@master/wp-content/uploads/2021/01/1611066945-8548749482a830d.webp" alt="file" />

### 字体样式1 宋体
```css
/*底部设置——网站底部自定义JS代码*/
<link href="https://fonts.lug.ustc.edu.cn/css2?family=Noto+Serif+SC:wght@400;700;900&display=swap" rel="stylesheet">
/*顶部设置——自定义CSS样式代码*/
h2 {
font-family: "Roman-55", -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Serif SC", "PingFang SC", "Microsoft Yahei UI", "Microsoft Yahei", sans-serif;
/*font-weight可以不要看需要*/
font-weight:400;
}
```
### 完成效果：↓
<img src="https://cdn.jsdelivr.net/gh/Littlemyself/hmfgu@master/wp-content/uploads/2021/01/1611045455454542.webp" alt="file" />

### 字体样式2 思源宋体-手机可用
```css
/*底部设置——网站底部自定义JS代码*/
<link href="https://fonts.loli.net/css2?family=Noto+Serif+SC&display=swap" rel="stylesheet">
/*顶部设置——自定义CSS样式代码*/
h2 { font-family: 'Noto Serif SC', serif;
/*font-weight字体加粗*/
font-weight:600;
}
```
```php
/*你也可以使用我使用jsdelivr加速的地址*/
<link href="https://cdn.jsdelivr.net/npm/googlefonts-hmau@1.0.1/css2.css?family=Noto+Serif+SC&display=swap" rel="stylesheet" />

```
### 完成效果：↓
<img src="https://cdn.jsdelivr.net/gh/Littlemyself/hmfgu@master/wp-content/uploads/2021/01/1611118513-4b76753498161ca.webp" alt="file" />

### 字体样式3 思源黑体
```php
/*底部设置——网站底部自定义JS代码*/
<link rel="stylesheet" href="https://fonts.lug.ustc.edu.cn/css?family=Noto+Sans+SC:100,300,400,500,700,900">
/*顶部设置——自定义CSS样式代码*/
h2 {
font-family: "Noto Sans SC";
/*font-weight字体加粗*/
font-weight:600;
}
```
### PiPlus全局换字体

```css
*思源宋体*/
p, small, h3, h4, h5, h6, h1, h2, input, body, button.btn.btn-primary.btn-block.rounded-xl.h-100, .mb-2.text-muted.down-title, textarea.form-control, label, .btn, textarea#comment, b, strong,.entry-content {
    font-family: 'Noto Serif SC', serif !important;
}
a {
    font-family: 'Noto Serif SC', serif;
    font-weight: 600;
}
code {
    font-family: Consolas,Monaco,'Andale Mono','Ubuntu Mono',monospace;
}
```
### Rizhuti-V2全局换字体
现在我的Rizhuti-V2主题使用的就是思源宋体

```css
html, body, div, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
    font-family: 'Noto Serif SC', serif;
}
```

### 编写css样式
把下面的代码保存成css文件，上传到主题css目录（主题名/assets/css）
我的文件名为：**css2.css**

```html
https://cdn.jsdelivr.net/gh/Littlemyself/dome@1.0/css2.css
```

### 实在不想放在functions.php里那就用link吧
Github和jsdelivr不倒，我的链接不倒。

```html
<link href="https://cdn.jsdelivr.net/gh/Littlemyself/dome@1.0/css2.css"; rel="stylesheet">
```
### 字体
下载所有需要的字体
把字体放在相应的fonts文件夹里，并修改src: url（字体文件地址）

```php
/* 样式参考写法 */
@font-face {
  font-family: 'Noto Serif SC';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(../fonts/H4chBXePl9DZ0Xe7gG9cyOj7oqP0dTpxZbB9E9gjjmzKvaeKHUTtJDWv3z-us4bxD8F5og.4.woff2) format('woff2');
  unicode-range: U+1f1e9-1f1f5, U+1f1f7-1f1ff, U+1f21a, U+1f232, U+1f234-1f237, U+1f250-1f251, U+1f300, U+1f302-1f308, U+1f30a-1f311, U+1f315, U+1f319-1f320, U+1f324, U+1f327, U+1f32a, U+1f32c-1f32d, U+1f330-1f357, U+1f359-1f37e;
}
```
### functions.php引入css样式
```php
wp_enqueue_style('css2', $_a . '/css/css2.css', array(), $_v,'all');
```

<img src="https://cdn.jsdelivr.net/gh/Littlemyself/hmfgu@master/wp-content/uploads/2021/01/b4fe1-1611322629-0604798c96c5942.webp" alt="file" />

### 清除缓存刷新网页试试看效果
<img src="https://cdn.jsdelivr.net/gh/Littlemyself/hmfgu@master/wp-content/uploads/2021/01/1de20-1611322951-1cd3b3fc669d31f.webp" alt="file" />
